# Generated by Django 5.1.6 on 2025-04-13 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrevista', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('receita_apro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('despesa_apro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('status_atendimento', models.CharField(max_length=20)),
                ('inicio_atendimento', models.DateField(blank=True, null=True)),
                ('termino_atendimento', models.DateField(blank=True, null=True)),
                ('lixo', models.CharField(blank=True, max_length=50, null=True)),
                ('limpeza_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('obs_limpeza', models.CharField(blank=True, max_length=2000, null=True)),
                ('agua', models.CharField(blank=True, max_length=50, null=True)),
                ('esgoto', models.CharField(blank=True, max_length=50, null=True)),
                ('obs_esgoto', models.CharField(blank=True, max_length=2000, null=True)),
                ('tipo_moradia', models.CharField(blank=True, max_length=20, null=True)),
                ('num_comodo', models.IntegerField(blank=True, null=True)),
                ('num_moradores', models.IntegerField(blank=True, null=True)),
                ('banheiro', models.CharField(blank=True, max_length=10, null=True)),
                ('construcao', models.CharField(blank=True, max_length=50, null=True)),
                ('televisor', models.BooleanField(blank=True, null=True)),
                ('geladeira', models.BooleanField(blank=True, null=True)),
                ('celular_smartphone_tablet', models.BooleanField(blank=True, null=True)),
                ('aparelho_som', models.BooleanField(blank=True, null=True)),
                ('maquina_lavar', models.BooleanField(blank=True, null=True)),
                ('carro_moto', models.BooleanField(blank=True, null=True)),
                ('dvd', models.BooleanField(blank=True, null=True)),
                ('computador_notebook', models.BooleanField(blank=True, null=True)),
                ('telefone_internet', models.BooleanField(blank=True, null=True)),
                ('obs_gerais', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('qtd_estoque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('instrucao', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=20, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=20, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.familia')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.familia')),
            ],
        ),
    ]
