# Generated by Django 5.1.6 on 2025-04-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterModelOptions(
            name='itemcesta',
            options={'verbose_name_plural': 'Itens da Cesta'},
        ),
        migrations.AlterField(
            model_name='itemcesta',
            name='quantidade',
            field=models.CharField(max_length=10),
        ),
    ]
