# Generated by Django 5.1.6 on 2025-04-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_parente_data_nascimento_alter_familia_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='status_atendimento',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Suspensa', 'Suspensa'), ('Aguardando Vaga', 'Aguardando Vaga')], default='Aguardando Vaga', max_length=20),
        ),
    ]
