# Generated by Django 5.1.6 on 2025-04-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_obs_esgoto_familia_obs_saneamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
