# Generated by Django 5.1.6 on 2025-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_familia_bairro_alter_familia_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='bairro',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familia',
            name='cep',
            field=models.CharField(default='a', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familia',
            name='cidade',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
