# Generated by Django 5.1.6 on 2025-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_familia_bairro_alter_familia_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
