# Generated by Django 5.1.6 on 2025-05-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_telefone_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='qtd_membros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
